spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 10.10.0.90
    port: 6379
    password: ulalalab12!@

  influxdb:
    url: "http://172.20.0.3:8086"
    username: ulalalab
    password: ulalalab12!@
    database: wimx
    udp-port: 7086
    connect-timeout: 1
    gzip: false
    read-timeout: 1
    retention-policy: autogen
    write-timeout: 1

  datasource:
    hikari:
      maximumPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    #url: "jdbc:postgresql://127.0.0.1:45432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

log-file-path:  d:/log/netty

server:
  port: 26080
#Netty
#netty:
#  tcp-port: 37080
#  http-port: 36081