spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 20
        min-idle: 10
        max-wait: -1
        time-between-eviction-runs: 5000
    host: 172.20.0.3
    port: 6379
    password: ulalalab12!@

  influxdb:
    #url: "http://external-host:8086"
    url: "http://172.20.0.2:8086"
    #url: "http://10.10.0.90:8086"
    username: ulalalab
    password: ulalalab12!@
    database: wimx
    udp-port: 7086
    connect-timeout: 5
    gzip: false
    read-timeout: 5
    retention-policy: autogen
    write-timeout: 5

  datasource:
    hikari:
      maximumPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

log:
  file:
    path: /data/logs

server:
  tcp:
    port: 37080
  http:
    port: 36080