spring:
  redis:
    lettuce:
      pool:
        max-active: 1
        max-idle: 10
        min-idle: 2
    host: 10.10.0.90
    port: 6379
    password: ulalalab12!@

  influxdb:
    url: "http://10.10.0.90:8086"
    username: ulalalab
    password: ulalalab12!@
    database: wimx
    udp-port: 7086
    connect-timeout: 1
    gzip: false
    read-timeout: 1
    retention-policy: autogen
    write-timeout: 1

  datasource:
    hikari:
      maximumPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

log-file-path:  d:/log/netty

log:
  file:
    path: d:/log/netty

server:
  port : 8081
  tcp-port: 27080
  http-port: 26080
  worker-count: 4
  boss-count: 1