spring:
  redis:
    host: 211.62.140.72
    port: 46379
    password: dak102938$&
  datasource:
    hikari:
      maximumPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    #url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    url: "jdbc:postgresql://127.0.0.1:45432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

#Log
#logging:
#  level:
#    root: info
##    jdbc.sqltiming: off
##    p6spy: off
##    org.springframework: info
#  file:
#    path: "d:/log/netty"

log-file-path:  d:/log/netty

#Netty
#netty:
#  tcp-port: 37080
#  http-port: 36081