spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 211.62.140.72
    port: 46379
    password: dak102938$&

  influxdb:
    url: "http://211.62.140.76:8086"
    username: ulalalab
    password: ulalalab12!@
    database: wimx
    udp-port: 8089

  datasource:
    hikari:
      maximumPoolSize: 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    #url: "jdbc:postgresql://127.0.0.1:45432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

server:
  port: 26088

#Log
#logging:
#  level:
#    root: info
##    jdbc.sqltiming: off
##    p6spy: off
##    org.springframework: info
#    com.ulalalab.snipe.infra.handler.ProcessHandler: info
#  file:
#    path: "d:/log/netty"

log-file-path: /data/logs

#Netty
#netty:
#  tcp-ip: 127.0.0.1
#  tcp-port: 9080
#  http-port: 36081