server:
  port: 38080

#spring :
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://127.0.0.1:3306/test_db?serverTimezone=Asia/Seoul"
#    username: root
#    password: root1234
#  influxdb:
#    url: http://127.0.0.1:8086
#    username: test
#    password: test1234
#    database: test_bucket
#    retention-policy: autogen

#Log
logging:
  level:
    root: info
    jdbc.sqltiming: info
    p6spy: info
  file:
    path: ""