server:
  port: 38080

spring :
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://211.62.140.76:5432/timescale?serverTimezone=Asia/Seoul"
    username: ulalalab
    password: ulalalab12!@

#Log
logging:
  level:
    root: info
    jdbc.sqltiming: info
    p6spy: info
  file:
    path: ""