#server:
  #error.whitelabel.enabled: false
  #port: 38080

spring :
#  datasource:
#    hikari:
#      auto-commit: true
#      connectionTimeout: 30000
#      maxLifetime: 1800000
#      poolName: HikariCP
#      readOnly: false
#      connectionTestQuery: SELECT 1
      #connection-test-query: SELECT 1
      #minimum-idle: 10
      #maximum-pool-size: 10
      #transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      #minimum-idle: 30
      #maximum-pool-size: 30
      #pool-name: pool-ulalalab

#  jpa:
#    database: postgresql
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        #hbm2ddl.auto: update
#        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    open-in-view: false
#    show-sql: true
#    generate-ddl: true
#    web:
#      resources:
#        add-mappings: false

#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        one-indexed-parameters: true

netty:
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100