server:
  error.whitelabel.enabled: false
  port: 38080

spring :
  datasource:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-ulalalab

  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: false
    generate-ddl: true
    web:
      resources:
        add-mappings: false

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true